//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login04.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Enrolments = new HashSet<Enrolment>();
            this.Studios = new HashSet<Studio>();
            this.CourseRatings = new HashSet<CourseRating>();
        }
    
        public int Id { get; set; }
        [Required]
        public string CourseName { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]

        public string ContactEmailForCourse { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{3})$", ErrorMessage = "Not a valid phone number, format xxxx-xxx-xxx")]
        public string ContactNumber { get; set; }
        [Required]
        [RegularExpression("^[^<>'\"]+$", ErrorMessage = "Special Character not allowed.")]
        public string CourseDescription { get; set; }
        [Required]
        public string StartDate { get; set; }
        [Required]
        public string EndDate { get; set; }
        [Required]
        public string Rating { get; set; }
        public int ServiceId { get; set; }
        [Required]
        public int StateId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrolment> Enrolments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Studio> Studios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRating> CourseRatings { get; set; }
    }
}
