//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login04.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enrolment
    {
        
        public int Id { get; set; }
        [Required]
        public System.DateTime EnrolDate { get; set; }
        [Required]
        public string UserId { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string UserEmail { get; set; }
        [Required]
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
