//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login04.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int Id { get; set; }
        [Required]
        [RegularExpression("^[^<>'\"]+$", ErrorMessage = "Special Character not allowed")]
        public string ServiceName { get; set; }
        [Required]
        [RegularExpression("^[^<>'\"]+$", ErrorMessage = "Special Character not allowed")]
        public string ContactEmail { get; set; }
        
        [Required(ErrorMessage = "You must provide a phone number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{4})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{3})$", ErrorMessage = "Not a valid phone number, format xxxx-xxx-xxx")]

        public string ContactNumber { get; set; }
        [Required]
        [RegularExpression("^[^<>'\"]+$", ErrorMessage = "Special Character not allowed")]
        public string ServiceDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}
