//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login04.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Studio
    {
        public int Id { get; set; }
        [Required]
        public string StudioName { get; set; }
        [Required]
        public string Location { get; set; }
        [Required]
        public string Latitude { get; set; }
        [Required]
        public string Longitude { get; set; }
        [Required]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Time),
    Display(Name = "Start Time", Description = "Number of Hours and Minutes after Midnight Central Timezone"),
    DisplayFormat(DataFormatString = @"{0:hh\:mm\:ss}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"((([0-1][0-9])|(2[0-1]))(:[0-5][0-9])(:[0-5][0-9])?)", ErrorMessage = "Time must be between 00:00 to 21:59")]
        public System.TimeSpan StartTime { get; set; }
        [Required]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Time),
    Display(Name = "Finish Time", Description = "Number of Hours and Minutes after Midnight Central Timezone"),
    DisplayFormat(DataFormatString = @"{0:hh\:mm\:ss}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"((([0-1][0-9])|(2[0-3]))(:[0-5][0-9])(:[0-5][0-9])?)", ErrorMessage = "Time must be between 00:00 to 23:59")]
        public System.TimeSpan FinishTime { get; set; }
        [Required]
        public string StudioDescription { get; set; }
        [Required]
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
